apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        ports:
          - containerPort: 3100
        args:
          - "-config.file=/etc/loki/local-config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: logging
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
      nodePort: 31100 