apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-metrics
  namespace: kafka
spec:
  kafka:
    version: 4.1.1
    # REMOVEMOS a metadataVersion para evitar o erro de "invalid" que vimos no log
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 30094
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      storage.layout: kraft
  entityOperator:
    topicOperator: {}
    userOperator: {}