apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-metrics
  namespace: kafka
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    metadataVersion: 3.7-IV4 # Define a versão de metadados para o KRaft
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 30094 # Porta para acesso externo
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      storage.layout: kraft
    storage:
      type: ephemeral # Dados temporários para aprendizado
  entityOperator:
    topicOperator: {}
    userOperator: {}