apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  namespace: kafka
  labels:
    strimzi.io/cluster: cluster-metrics
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral