apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30180
  selector:
    app: kafka-ui