apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: joao-admin
  namespace: kafka
  labels:
    strimzi.io/cluster: meu-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: All
        host: "*"