apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: joao-admin
  namespace: kafka
  labels:
    strimzi.io/cluster: cluster-metrics
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: All # <--- Garantir que está aqui
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All # <--- Garantir que está aqui
        host: "*"
      - resource:
          type: cluster
        operation: All # <--- Adicione explicitamente aqui também!
        host: "*"