apiVersion: v1
kind: Secret
metadata:
  name: zabbix-secret
type: Opaque
data:
  POSTGRES_PASSWORD: WmFiYml4UGFzc3dvcmQ= # Base64 de "ZabbixPassword"
  POSTGRES_USER: emFiYml4 # Base64 de "zabbix"
  POSTGRES_DB: emFiYml4 # Base64 de "zabbix"