apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:latest
        env:
        - name: ZBX_HOSTNAME
          value: "k3s-observability"
        - name: ZBX_SERVER_HOST
          value: "127.0.0.1,192.168.1.20" # Adicionei o loopback e seu IP real
        - name: ZBX_PASSIVE_ALLOW
          value: "0.0.0.0/0"
        securityContext:
          privileged: true
        ports:
        - containerPort: 10050
          hostPort: 10050
          name: zabbix-agent