apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: monitoring 
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      hostNetwork: true 
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:7.4-latest
        ports:
        - containerPort: 10050
          name: zabbix-agent
        env:
        - name: ZBX_HOSTNAME
          value: "k3s-node-01"
        - name: ZBX_SERVER_HOST
          value: "192.168.1.20" 
        securityContext:
          privileged: true 