apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://seu-repo-git.com/sua-organizacao/zabbix-k8s'
    targetRevision: HEAD
    path: zabbix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true