name: Zabbix Helm CI

on:
  push:
    paths:
      - "zabbix/zabbix-kubernetes-helm/values.yaml"
  pull_request:

env:
  CHART_URL: https://cdn.zabbix.com/zabbix/integrations/kubernetes-helm/7.4/zabbix-helm-chart-1.6.8.tgz
  VALUES_FILE: zabbix/zabbix-kubernetes-helm/values.yaml

jobs:
  helm-ci:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Helm version
      run: helm version

    - name: Install kubeconform
      run: |
        curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
        sudo mv kubeconform /usr/local/bin

    - name: Download Zabbix Chart
      run: |
        curl -L $CHART_URL -o chart.tgz
        tar -tzf chart.tgz | head

    - name: Lint Helm Chart
      run: |
        helm lint chart.tgz \
        -f $VALUES_FILE

    - name: Render Helm templates
      run: |
        helm template zabbix chart.tgz \
        -f $VALUES_FILE \
        --namespace monitoring \
        > rendered.yaml

    - name: Validate Kubernetes manifests
      run: |
        kubeconform -summary rendered.yaml

    - name: Show manifest preview
      run: |
        echo "First resources generated:"
        grep "kind:" rendered.yaml | head

    - name: Upload rendered manifests
      uses: actions/upload-artifact@v4
      with:
        name: zabbix-k8s-manifests
        path: rendered.yaml